- name: Run redis tasks
  hosts: clusord
  become: yes
  user: rack
  gather_facts: yes

  roles:
    - firewalld
    - cluster-common
    - redis

- name: Run cluster master tasks
  hosts: ordclusNode01
  become: yes
  user: rack
  gather_facts: yes

  roles:
    - cluster-master
