---

- name: Add eth2 interface to trusted firewalld zone
  firewalld:
    zone: trusted
    interface: eth2
    permanent: yes
    state: enabled

- name: Allow redis traffic
  firewalld:
    zone: trusted
    service: redis
    state: enabled
    permanent: yes
