---

- name: Add eth2 interface to trusted firewalld zone
  firewalld:
    zone: trusted
    interface: eth2
    permanent: yes
    state: enabled

# - name: Allow redis traffic
#   firewalld:
#     port: 6379/tcp
#     # source: 172.26.184.0/24
#     interface: eth2
#     state: enabled
#     permanent: yes

- name: Allow redis traffic
  firewalld:
    zone: trusted
    service: redis
    state: enabled
    permanent: yes
