---

- name: install PCS cluster pkgs and requirements
  yum:
    name: "{{ item }}"
    state: latest
  loop:
    - pcs
    - dlm
    - gcc
    - git

- name: install python package mgr (pip)
  yum:
    name: python2-pip
    state: latest

# - name: Add all hosts to respective /etc/hosts files
#   blockinfile:
#     dest: /etc/hosts
#     content: "{{ lookup('template', 'hosts.j2') }}"
#     state: present

- name: Ensure cluster services are active and start on boot
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - pcsd

- name: download SSH fencing script
  git:
    repo: https://github.com/nannafudge/fence_ssh.git
    dest: /tmp/fence_ssh/

- name: copy SSH fencing script into place
  copy:
    src: /tmp/fence_ssh/fence_ssh
    dest: /usr/sbin/fence_ssh
    remote_src: yes
    mode: 0700
    owner: root
    group: root
